apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
  namespace: default # Replace with your namespace if different
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: cache-image:latest # Replace with your container image
        ports:
        - containerPort: 6379 # Example port for a cache service
