apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-app-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: my-app-deployment # Replace with the label of your deployment pods if different
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {} # Allow traffic from any pod within the same namespace
    - podSelector:
        matchLabels:
          app: trusted # Allow traffic from a specific pod with the label app=trusted
  egress:
  - to:
    - podSelector: {} # Allow traffic to any pod within the same namespace
